- name: Add apt key
  tags: install
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
- name: Add apt repository
  tags: install
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
- name: Install MongoDB
  tags: install
  apt:
    name: mongodb-org
    state: present
    update_cache: true
- name: Enable MongoDB
  tags: install
  systemd:
    name: mongod
    state: restarted
    enabled: true
