---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: "0644"
    owner: root
  notify: Reload puma
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    mode: "0644"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
- name: Enable puma
  systemd:
    name: puma
    enabled: true
    daemon_reload: true
