---
- name: Clone
  hosts: app
  tasks:
    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: 5c217c5
