---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
          - git
        state: present
