---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.128.0.18
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: "0644"
      tags: db-tag
      notify: Restart mongod
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
        owner: root
      tags: app-tag
      notify: Reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: "0644"
      tags: app-tag
    - name: Enable puma
      become: true
      systemd:
        name: puma
        enabled: true
        daemon_reload: true
      tags: app-tag
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: Reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag

  handlers:
    - name: Restart mongod
      become: true
      service:
        name: mongod
        state: restarted

    - name: Reload puma
      become: true
      systemd:
        name: puma
        state: restarted
